dist: trusty
sudo: false
language: node_js
node_js:
  - "8"
before_install:
  #- sudo apt-get -qq update
  #- curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  #- sudo apt-get install -y nodejs
before_script:
  - npm install
script: npm run lint
