language: node_js
before_install:
  - sudo apt-get -qq update
  #- curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  #- sudo apt-get install -y nodejs
before_script:
  - sudo nvm use lts
script: npm run lint
