dist: trusty
sudo: false
language: node_js
cache:
  bundler: true
  directories:
  - node_modules
node_js:
  - "8"
before_install:
  #- sudo apt-get -qq update
  #- curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  #- sudo apt-get install -y nodejs
before_script:
  - npm install
script:
  - npm run lint
  - npm run build -- --mode=production --buildNumber=$TRAVIS_BUILD_NUMBER --version=$VERSION --commit=`git rev-parse --short HEAD`
