export const OPEN_LEFT_SIDEBAR = 'OPEN_LEFT_SIDEBAR';
export const CLOSE_LEFT_SIDEBAR = 'CLOSE_LEFT_SIDEBAR';
export const LOAD_WEB3_PROVIDER = 'LOAD_WEB3_PROVIDER';
export const WEB3_PROVIDER_IS_NOT_AVAILABLE = 'WEB3_PROVIDER_IS_NOT_AVAILABLE';
export const REQUEST_ACCOUNTS = 'REQUEST_ACCOUNTS';
export const APPLICATION_INITIALIZED = 'APPLICATION_INITIALIZED';
